### ISSUE TITLE
why alomst libraries not work with megacore

### ISSUE THREAD

**Issue by fadi0albaghdadi** [MCUdude/MegaCore#163]
why almost libraries not work with megacore
like library WS2812

**Comment by MCUdude** [comment]
Because many libraries aren't written to support "Non-Ardunio" hardware like the ATmega128. It's not something I can do much about, the library authors either have to adapt their libraries to work with MegaCore hardware, or they'll have to write architecture-neutral libraries.

The FastLED library That I've used to drive addressable LEDs like the WS2812B [lacks hardware definitions for the ATmega128](https://github.com/FastLED/FastLED/blob/master/src/platforms/avr/fastpin_avr.h).
