### ISSUE TITLE
Interrupts

### ISSUE THREAD

**Issue by spa-sam** [MCUdude/MegaCore#29]
Use the rfm69. Also a problem with interrupts. I have used pin4. Put the number of interrupts 4, but transfer no. What could be the problem?

#define RFM69_CS 8
#define RFM69_IRQ 4 //pin
#define RFM69_IRQN 4// ?

RFM69 radio = RFM69(RFM69_CS, RFM69_IRQ, true, RFM69_IRQN);

Checked! Only works 6 interrupt! Why? What am I doing wrong? How to use pin 4?

**Comment by MCUdude** [comment]
This is not a MegaCore related issue. The problem is that the RFM69 library doesn't support the ATmega64 or the ATmega128 bu default. I don't own a RFM69 compatible radio, so I've no way to test this. If you want to use the ATmega64/128 with this library you should create an issue at the [RFM69 repo](https://github.com/LowPowerLab/RFM69) instead.
