### ISSUE TITLE
Can't find Mega2561 after installation of MegaCore,json

### ISSUE THREAD

**Issue by PingCube** [MCUdude/MegaCore#30]
Hi nice work but i can't finde the mega2561 or the mega1281 in Boardmanager after installation. I use the version 1.0.5

regards

elektronikjogi

![image](https://cloud.githubusercontent.com/assets/7677419/22804445/6197a5f2-ef19-11e6-8a5a-689e6103307d.png)

**Comment by per1234** [comment]
The problem is there hasn't been a release of MegaCore since support for ATmega2561 and ATmega1281 was added. To use those boards you will need do a manual instruction following these instructions:
https://github.com/MCUdude/MegaCore#manual-installation
It's probably best to remove the Boards Manager installation of MegaCore because it might conflict with the manual installation.

**Comment by PingCube** [comment]
Thanks for your help

Best regards

elektronikjogi

**Comment by MCUdude** [comment]
The latest boards manager version (v1.0.6) is now available, with Atmega1281/2561 support!
