### ISSUE TITLE
Can't allow INT for WD

### ISSUE THREAD

**Issue by DallySon** [MCUdude/MegaCore#50]
Hello,

Cant allow int for WD timer.

WDTCR |= _BV(WDIE);

compilator says:'WDIE' was not declared in this scope. 

On atmega328 its working:  WDTCSR |= _BV(WDIE);

Help me please...

**Comment by MCUdude** [comment]
Have in mind that the ATmega328p and the ATmega128 may have different register and bit names. You should look this up in the datasheets. When it comes to the WDIE error, it's because the ATmega128 doesn't support "regular" WDT interrupts. The WDT can only be used for resetting the microcontroller, nothing else. If you need the WDIE, you'll have to use an ATmega1281.
